import { DSL } from "./types";

export function generateTypeScript(dsl: DSL): string {
  const { name, states, computed = {}, handlers = {}, actions = {}, ui } = dsl;

  const stateTypes = Object.entries(states)
    .map(([name, def]) => `  ${name}: ${getTypeScriptType(def.type)}`)
    .join("\n");

  const computedTypes = Object.keys(computed)
    .map(
      (name) => `  ${name}: ${getComputedReturnType(computed[name], states)}`
    )
    .join("\n");

  const actionTypes = Object.entries(actions)
    .map(([name, action]) => `  ${name}: () => Promise<void>`)
    .join("\n");

  const handlerTypes = Object.keys(handlers)
    .map((name) => `  ${name}: (event?: any) => void`)
    .join("\n");

  return `// Auto-generated by PromptCC
// ${new Date().toISOString()}

import { usePromptCC } from '@promptcc/engine'

export const dsl = ${JSON.stringify(dsl, null, 2)}

export interface DSLState {
${stateTypes}
}

export interface DSLComputed {
${computedTypes}
}

export interface DSLHandlers {
${handlerTypes}
}

export interface DSLActions {
${actionTypes}
}

export function useDSL() {
  return usePromptCC(dsl)
}

// 辅助类型
${getTypeScriptType}
`;

  function getTypeScriptType(type: string): string {
    switch (type) {
      case "string":
        return "string";
      case "number":
        return "number";
      case "boolean":
        return "boolean";
      case "object":
        return "any";
      case "array":
        return "any[]";
      default:
        return "any";
    }
  }

  function getComputedReturnType(
    expr: string,
    states: Record<string, any>
  ): string {
    // 简单推断类型
    if (expr.includes("&&") || expr.includes("||") || expr.includes("!")) {
      return "boolean";
    }
    if (expr.includes(".length")) {
      return "number";
    }
    return "any";
  }
}
